"""Extract CWASA's known HamNoSys tag set from allcsa.js and scan data/*.sigml for unknown tags.

Usage:
    python3 scripts/scan_unknown_hns_tags.py [--fruit-only]

Outputs a sorted table of unknown tag occurrences per file.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ALLCSA = REPO_ROOT / "public" / "cwa" / "allcsa.js"
DATA_DIR = REPO_ROOT / "data"

CONTAINER_TAGS = {
    "hamnosys_manual",
    "hamnosys_nonmanual",
    "hamgestural_sign",
    "hns_sign",
    "sigml",
}


def extract_known_tags() -> set[str]:
    """Pull all tag names embedded in HNSDefs.tokenNameMap."""
    src = ALLCSA.read_text()
    start = src.index("HNSDefs.tokenNameMap = [")
    end = src.index("];", start)
    section = src[start:end]
    known: set[str] = set()
    for match in re.finditer(r'"([^"]*)"', section):
        for name in match.group(1).split():
            if name:
                known.add(name)
    return known


def scan_file(path: Path, known: set[str]) -> dict[str, list[int]]:
    """Return {unknown_tag: [line_numbers]}."""
    unknown: dict[str, list[int]] = {}
    for lineno, line in enumerate(path.read_text().splitlines(), start=1):
        for tag in re.findall(r"<(ham[A-Za-z][\w]*)", line):
            if tag in CONTAINER_TAGS or tag in known:
                continue
            unknown.setdefault(tag, []).append(lineno)
    return unknown


def scan_repo() -> dict[Path, dict[str, list[int]]]:
    known = extract_known_tags()
    report: dict[Path, dict[str, list[int]]] = {}
    for path in sorted(DATA_DIR.glob("*.sigml")):
        u = scan_file(path, known)
        if u:
            report[path] = u
    return report


def render_markdown(report: dict[Path, dict[str, list[int]]]) -> str:
    lines = [
        "# Database health — unknown HamNoSys tags in `data/*.sigml`",
        "",
        "Generated by `scripts/scan_unknown_hns_tags.py`. Any tag listed below is a",
        "name CWASA's shipped `allcsa.js` (HNSDefs.tokenNameMap) does not recognise.",
        "When the avatar processes such a sign, the tag is silently dropped — and",
        "the remaining HamNoSys sequence may fail tree-parsing, which surfaces as",
        "`mismatched input '[object Object]'`.",
        "",
        "Prompt 3 ships a runtime validator that skips affected signs and surfaces a",
        "clear error instead of emitting broken XML. Fixing the underlying data is",
        "owned by prompt 7.",
        "",
        "## Totals",
        "",
    ]
    totals: dict[str, int] = {}
    for tags in report.values():
        for tag, locs in tags.items():
            totals[tag] = totals.get(tag, 0) + len(locs)
    if totals:
        lines.append("| tag | occurrences | likely fix |")
        lines.append("|---|---|---|")
        hints = {
            "hampalmud": "split into `<hampalmu/>` + `<hampalmd/>`, or use `<hamreplace/>` + `<hampalmd/>` if a rotation is intended",
            "hammoveudl": "split into valid motion tags, e.g. `<hammoveul/>` or `<hammoved/>` + `<hammovel/>`",
            "hampinchopen": "rename to `<hampinch12open/>` (or `<hamceeopen/>` if a cee shape is intended)",
            "hamupperarm": "rename to `<hamUpperarm/>` (capital U — CWASA tag is case-sensitive)",
            "hamindxfinger": "typo — should be `<hamindexfinger/>`",
            "hamfinger234": "not a valid handshape — CWASA has `<hamfinger23/>` (2+3) and `<hamfinger2345/>` (2+3+4+5)",
        }
        for tag, count in sorted(totals.items(), key=lambda x: -x[1]):
            lines.append(f"| `<{tag}/>` | {count} | {hints.get(tag, 'investigate — not in CWASA spec')} |")
    else:
        lines.append("_No unknown tags detected._")
    lines.extend(["", "## Per-file breakdown", ""])
    if not report:
        lines.append("_All `data/*.sigml` files use only tags CWASA recognises._")
    else:
        for path, tags in sorted(report.items()):
            rel = path.relative_to(REPO_ROOT)
            lines.append(f"### `{rel}`")
            lines.append("")
            lines.append("| tag | count | first occurrences (line numbers) |")
            lines.append("|---|---|---|")
            for tag, locs in sorted(tags.items(), key=lambda x: -len(x[1])):
                sample = ", ".join(str(n) for n in locs[:5])
                more = f" (+{len(locs) - 5} more)" if len(locs) > 5 else ""
                lines.append(f"| `<{tag}/>` | {len(locs)} | {sample}{more} |")
            lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-report", action="store_true", help="write docs/polish/03-database-health.md")
    parser.add_argument("--fruit-only", action="store_true", help="only check LSF FRUIT entry")
    args = parser.parse_args()

    known = extract_known_tags()

    if args.fruit_only:
        lsf = DATA_DIR / "French_SL_LSF.sigml"
        text = lsf.read_text()
        m = re.search(r'<hns_sign gloss="FRUIT">(.*?)</hns_sign>', text, re.DOTALL)
        if not m:
            raise SystemExit("FRUIT entry not found in LSF file")
        block = m.group(0)
        tags = set(re.findall(r"<(ham[A-Za-z][\w]*)", block))
        unknown = [t for t in tags if t not in CONTAINER_TAGS and t not in known]
        print(f"FRUIT tags: {sorted(tags)}")
        print(f"Unknown  : {sorted(unknown)}")
        return

    report = scan_repo()
    md = render_markdown(report)
    if args.write_report:
        out = REPO_ROOT / "docs" / "polish" / "03-database-health.md"
        out.write_text(md)
        print(f"Wrote {out}")
    else:
        print(md)


if __name__ == "__main__":
    main()
